package com.javatpoint.exceptions;

public class MultipleCatchBlocks {
	
	public static void main(String[] args) {
		try {
		int a[] = new int[4];
		a[4] = 100/0;
		}catch(Exception f) {System.out.println(f.getMessage());
		}catch(ArrayIndexOutOfBoundsException n) {System.out.println(n.getMessage());
		}catch(ArithmeticException e) {System.out.println(e.getMessage());
		}finally {System.out.println("Finally block executed");}
		}
	}
